name: CI/CD - Frontend Only Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build frontend locally
        run: docker build -t crud-frontend:latest ./frontend

      - name: Deploy to Docker Swarm
        run: docker stack deploy -c docker-stack.yml crud-app
